// © 2024 Pulse Core Interactive. All rights reserved.

#pragma once

UENUM(BlueprintType)
enum class EActionState : uint8
{
	ACTION_STATE_UNKOWN,

	ACTION_UNOCCUPIED,
	ACTION_IDLE_UNARMED,
	ACTION_IDLE_RANGED_WEAPON,
	ACTION_IDLE_MELEE_WEAPON,
	ACTION_ATTACKING,
	ACTION_AIMING,
	ACTION_AIMING_AND_RUNNING,
	ACTION_SHOOTING,
	ACTION_SHOOTING_AND_RUNNING,
	ACTION_MELEE_ATTACKING,
	ACTION_JUMPING,
	ACTION_PICKING_UP_WEAPON,
	ACTION_SHEATHING_UNSHEATHING,

	NUM_ACTIONS
};